#! /bin/env python3 

#Task 1: Arithmetic Operators
#Create two variables a and b with numeric values.
#Calculate the sum, difference, product, and quotient of a and b.
#Print the results.
a =2
b =3
print((a+b),(a-b),(a*b),(a/b))


##################################
#Compare the values of a and b using the following comparison operators: <, >, <=, >=, ==, and !=.
#Print the results of each comparison.
print((a<b),(a>b),(a<=b),(a>=b),(a==b))
#########################################
#Create two boolean variables, x and y.
#Use logical operators (and, or, not) to perform various logical operations on x and y.
#Print the results.
x=True
y=False
print((x and y ),(x or y ),(not x) ,(not y))

###################################


x = 10
if x > 15:
    print ("x is greater than 15")
elif x>5:
    print ("x is greater than 5 but not greater than 15 ")
else:
    print ("x is not greater than 5")
