#!/bin/bash
environments=("dev" "staging" "prod")
for env in "${environments[@]}"; do
    deploy_configuration "$env"
done
#######################################
databases=("db1" "db2" "db3")
for db in "${databases[@]}"; do
    create_backup "$db"
done
#########################################
log_files=("app.log" "access.log" "error.log")
for log_file in "${log_files[@]}"; do
    rotate_and_cleanup_logs "$log_file"
done
