#!/bin/env python3



fruits = ["apple","banana","cherry"]

for fruit in fruits :
    print(fruit)
#######################################
count  = 0
while count < 5 :
    print (count)
    count +=1
####################################
